### ISSUE TITLE
On forking and change of license

### ISSUE THREAD

**Issue by raimue** [asciidoc3/asciidoc3-deprecated#1] opened 2018-04-25 00:08 UTC
Hello,

it is great to see someone willing to work on porting AsciiDoc to Python 3!

It looks like you modified the original source code of asciidoc, but also dropped all history from the repository by importing a snapshot of the source code. In my opinion, this is a bad start for a fork, as this takes away the chance to explore the history of the project. Could your changes be applied on top of the current state of AsciiDoc (for Python 2.x) to preserve the history?

You also changed the license to Affero GPLv3. As far as I see, the licensing statement for AsciiDoc does not even contain the "or any later version" phrasing, so it is strictly licensed as GPLv2 only. IANAL, but I highly doubt that Affero GPLv3 would even qualify as a later version of GPLv2. Do you have permission from all previous contributors to change the license?

Copying documentation from the old AsciiDoc website into your user guide, without any mention of the source or names of the original authors is also quite rude and questionable.

Overall I wonder why this project is not a continuation of the existing work at https://github.com/asciidoc/asciidoc3? See also https://github.com/asciidoc/asciidoc/issues/83. Is compatibility with Python 3 alone worth a fork and a split of the community?

**Comment by obilodeau** [comment] 2018-04-28 16:17
You can't relicense code you didn't write: https://softwareengineering.stackexchange.com/questions/66254/can-a-user-relicense-lgpl-as-gpl-or-gpl-as-agpl 

You can upgrade AsciiDoc's original code to GPLv3 (based on the evidence you provided) but you can't relicense it to AGPL.

Beyond what you can and can't do. I think the AGPL is too drastic and it would hinder the adoption of the AsciiDoc language. Imagine a popular proprietary web service written in Python that would like to use your code (extract it out to use it as a lib), the AGPL would poison their code base and they would need to make the whole service open source. You lose the opportunity of users that way.

**Comment by raimue** [comment] 2018-05-01 14:07
I see, the statement in [COPYRIGHT](https://github.com/asciidoc/asciidoc/blob/8.6.9/COPYRIGHT) is in fact different from what is stated in [README](https://github.com/asciidoc/asciidoc/blob/8.6.9/README.txt#L31-L35). I originally only looked at the README, but I agree that COPYRIGHT should take precedence. So upgrading the license to GPLv3 is allowed.

However, I am still not sure about switching from GPLv3 to AGPLv3. From https://www.gnu.org/licenses/license-list.html#AGPLv3.0:
> [...] you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, or vice versa. However, you are allowed to combine separate modules or source files released under both of those licenses in a single project, [...]

**Comment by asciidoc3** [comment] 2018-05-02 21:44
I think we agree that upgrading AsciiDoc3 to GPLv3 is not the point – that‘s ok. My intention was (and is) to make the software „as free as possible“ (to say in my own words).
And, @raimue, I am still not sure about switching from GPLv3 to AGPLv3, too. The link you provided talks about code which is released under the terms of GPLv3 (AGPLv3 vice versa). But the code here (which I modified, ...) was released under the terms of GPLv2 or later, I upgrade to GPL v3 and then to AGPLv3 in the same logical second. And the ‚compatibility matrix‘ [https://www.gnu.org/licenses/gpl-faq](https://www.gnu.org/licenses/gpl-faq) says: ‚statement about compatibility is true for AGPLv3 as well.‘ Perhaps seeking a lawyer would help, but I have my doubts: asking three lawyers gives you four answers back ...
I do not insist on AGPL, I think about changing this to GPLv3 asap ...

**Comment by asciidoc3** [comment] 2018-05-10 19:40
Back to licensing and closing:
I started a question at [https://opensource.stackexchange.com/questions/6816/gplv2-or-later-upgrade-to-agplv3](https://opensource.stackexchange.com/questions/6816/gplv2-or-later-upgrade-to-agplv3) and asked a ‚well-established‘ lawyer off the record. Both answers confirmed my resolution to choose the AGPLv3.
The trick is in my words: there was never a software under GPLv3 until now, AsciiDoc is GPLv2 or later. There is no ‚switching from GPLv3 to AGPLv3‘, because there is/was no GPLv3! So, according to the ‚compatibility matrix‘ (see above), you may upgrade from GPLv2 to AGPLv3. All right.
Thx for your qualified statements.

**Comment by obilodeau** [comment] 2018-05-11 04:38
You can't relicense code you didn't write because you don't own the copyright, you have the right to use and modify the code under its license. It's two different things.

I can't contribute to this both on moral grounds (the AGPL is too copyleft to be used for infrastructure-level code) and on legal grounds (you are performing copyright infringement). I'll show myself out.

Good luck with your fork.

**Comment by asciidoc3** [comment] 2018-05-11 09:06
I encounter some kind of ‚shitstorm‘ since my statement about choosing the AGPLv3. All right, I do not insist on AGPL, the forthcoming release of AsciiDoc3 will be ‚GPLv3 or later‘ ...

**Comment by mojavelinux** [comment] 2018-05-26 06:25
This fork is in violation with the license of AsciiDoc Python. In particular, you have

1. removed the history of the project (master, branches and tags)
2. removed the authorship, both through (1) and by removing the author and copyright from the README and COPYRIGHT files
3. changed the license without permission from the original authors and contributors

If you do not bring the fork into compliance with the license of AsciiDoc Python, the authors of AsciiDoc Python will work with the Software Freedom Law Center (or equivalent entity) to have this fork taken down. Consider this to be the official request in writing.

**Comment by asciidoc3** [comment] 2018-06-01 21:14
Hello all,
I was offline for about 14 days (by my own choice - yes indeed this is possible), but I‘ll cover the above questions/issues within the next few days (this weekend probably) ...

**Comment by asciidoc3** [comment] 2018-06-03 21:57
Hello again,
you see me surprised and disturbed by many of the above posts. What is going on here?
Before I can answer detailed please help me with two questions to ensure that we are talking about the same thing:
- Who owns the copyright of AsciiDoc (here: the Python2 version of course) and under what license it is released?
My answer – see tarball "asciidoc-8.6.9.tar.gz" https://sourceforge.net/projects/asciidoc/files/latest/download (last visit 2018-June-3): „Copyright (C) 2000-2007 Stuart Rackham Email: srackham@gmail.com This program is free software ...  GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 

- **@mojavelinux** and others: What can I do to make you happy again (not ironically)? Changing license to GPLv2, remove the repo asciidoc3/asciidoc3 or write pull requests to asciidoc/asciidoc3 or what else?

**@Petr Prikryl** Thanks for your „Please, folks, calm down a bit.“ I appreciate your „offer myself as a mediator, and I will do first steps soon.“

**Comment by elextr** [comment] 2018-06-03 23:12
> What is going on here?

Just normal open source public development processes, there are comments on issues with the project.  

Licenses are a sensitive topic in the open source community, they are all that ensures projects remain open source.  Hence when people see a mistake they try to make the originator aware of that, and because they __care__ about the projects remaining open source, that point may be made somewhat forcefully.

> Who owns the copyright of AsciiDoc

Stuart owns copyright of most, but all the contributors continue to own copyright of their contribution as recorded in the Git history, the Asciidoc project has no copyright assignment to Stuart.  Thats part of why @mojavelinux was so cross about your erasing history, you have erased the record of copyright ownership and effectively assigned it to someone else.

> What can I do

If you really want to keep this as a separate project then you must fix the license problem and restore history.  The simplest way to fix the license would be to just make the whole project GPLv2+, or, as I said above you might want to make new work GPLv3 whilst old content still remains under the GPLv2+, but then you have to state that in the headers and supply copies of both licenses.

But probably the best solution is to contribute to `asciidoc/asciidoc3` (which will soon be renamed to `asciidoc/asciidoc-py3`, please don't use that name yourself, it will cause confusion).  The more people communicate and co-operate to improve one version of software, the better off everyone is.

The problem with the asciidoc3 name (which applies to `asciidoc/asciidoc3` as well, thats why it will be renamed) is that it may be confused with being a later version of _Asciidoc_ not the original version of Asciidoc using a later version of _Python_.

There are plans to define the Asciidoc language independent of any specific implementation (like commonmark for markdown) and so its important not to confuse users between implementations, and versions of the language specification.

**Comment by mojavelinux** [comment] 2018-06-04 09:13
Well said, @elextr. The only point I have to add at this time is that preserving copyright notices isn't specific to open source licenses. This point is stated quiet clearly on the OSI site.

https://opensource.org/faq#preserve-copyright-notices

**Comment by asciidoc3** [comment] 2018-06-04 23:03
@elextr @mojavelinux
A short additional question: you say „... all the contributors continue to own copyright of their contribution as recorded in the Git history ...“ Maybe, I have no doubt about this, but my work began with tarball 8.6.9 – and there you see „Copyright 2002-2013 Stuart Rackham. ... GNU GPLv2 or later“ (we had this before). Why is there no „and contributors“ (see here:  https://opensource.stackexchange.com/questions/5508/what-does-and-contributors-in-the-copyright-byline-imply)?
And to underline something again: I didn‘t „erase history“: the history is the known history of „8.6.9“, all changes in the source between 8.6.9 and the release of Asciidoc3-3.0.1 are my work. So the history is completely documented, everybody - who is interested in this - may reproduce this (my comments are written down here: https://asciidoc3.org/asciidoc3port.pdf)
I want to be rid of this discussion – I have other things to do, believe me. Presumably I‘ll change AsciiDoc3 license very soon to GPLv2+. „We are all consenting adults here.“

**Comment by mojavelinux** [comment] 2018-06-04 23:48
You can want copyright discussion to go away, but unless you come into compliance with the law, it doesn't work that way.

You cannot remove copyright and license notices that existed in the tarball. You have done that in the following files (not an exhaustive list)

* https://github.com/asciidoc3/asciidoc3/blob/master/README.md
* https://github.com/asciidoc3/asciidoc3/blob/master/COPYRIGHT
* https://github.com/asciidoc3/asciidoc3/blob/master/help.conf

You've also changed the license in many files. In fact, in at least one place you incorrectly cite the license of the original work as MIT (see https://github.com/asciidoc3/asciidoc3/blob/f5831ba11925e515ed9561f3e3fddabf79f81504/a2x3.py). My understanding is that you could use GPLv3 (as the GPLv2 license states), but you absolutely cannot change the license to AGPLv3.

There's also a trademark issue at hand here. You are using the original name of the software (adding a 3 does not make it different), yet running it as a separate project. You'll have to rename the project if you don't want to contribute your changes back upstream.

I think you really need to ask yourself if you are trying to help or harm AsciiDoc Python. Your current path is damaging the project substantially because you have created both controversy and confusion. If you have no interest in being part of the community, then you must come into compliance with the law and rename the project. If you'd like to contribute your changes upstream and rejoin the project, I invite you to do so (and I'm sure Lex does as well). If you decided on the latter, it would turn this situation around and generally benefit the AsciiDoc Python community.

**Comment by elextr** [comment] 2018-06-05 00:33
@asciidoc3 its unfortunate that you started with a tarball.  Tarballs are just a distribution mechanism for a snapshot of the project, they do not contain the history of the changes that have been made to get to the point and who made them, and are not intended to do so.  A tarball is simply the result of those changes. 
 They are not the project official source record, that is the Git repository.  So you "erased history" by using a tarball and not using the Git repository as your source, and it is that history that identifies who has copyright to which parts of the source.

The answer on the stackexchange you quote provides answers to most of your points:

1. although it can be useful to add "and contributors" to a copyright notice, it is not required, in fact no copyright notice at all is required in law.  Copyright to the creator comes into existence as soon as a work is created, and remains with the creator until explicitly transferred irrespective of the existence or lack of any such notices.  Since no notice is required or the notice may not list all ownerships, it is required of anyone who uses a work to take reasonable care to check the copyright ownership, information which is publicly available in the Git repository, but which your use of the tarball has removed.

2. Github terms of service make it explicit that contributions remain owned by the contributors and that such contributions are licensed under the repository license ie GPLv2+ in the Asciidoc case.

The technical mechanism to become compliant is to simply fork (in the github sense of the word) the Asciidoc repository, that will then have all the records of who owns which contributions.  Then just apply your changes (except the ones breaking the license of course) to that clone instead of a tarball and publish it under a suitable name.  That is a simple exercise of git.

But I would like to ask a non-technical question?  What is your intention for this project, is it:

1. for your own fun and learning (neat, but please make that explicit so people won't rely on it)

2. a service to users of Asciidoc Python as a maintained version that maintains existing capability (thanks, thats appreciated, but the issues here are making it unusable in that role, and there is another version on the Asciidoc website)

3. a longer term project intended to contribute to the development of Asciidoc (are you sure you have time to maintain it)

In both cases 2 and 3 it is necessary to communicate with the Asciidoc community, preferably before you published a fait accompli, so they could have advised you and you could have avoided the mistakes and this whole conversation.  And then those making the version on the Asciidoc website and yourself could have cooperated on a single version making everybodys workload smaller.  Instead there is now two ports of Asciidoc Python to Python 3, causing confusion for users.

And in all cases let me encourage you to communicate communicate communicate, we all have days where we forget that, and do something thats "obvious" to us, only to have others have a different opinion.  Asking first saves us all heartache, that should be the big takeaway from this experience, both for this and all other projects you want to be involved in.

**Comment by asciidoc3** [comment] 2018-06-06 20:56
@elextr @mojavelinux
(again you two - are you playing good cop/bad cop ;-) ?! bsf: Your posts (and all the others, too) got me thinking. I'll come back tomorrow with the conclusion (local Munich Time 11 pm - weary with working). Guess, the result will ease the situation.

**Comment by ff2000** [comment] 2018-07-01 11:36
Just out of curiosity: I always thought having my GPL sources available in git (or any SCM) was optional. Even having a downloadable tarball is no must. The key is to offer the sources, even if it's just on request and by direct submission (via E-Mail, USB-stick, ...) Of course this stays true for forks.
Naming forks of course is a different thing.
Also many projects have a CONTRIBUTORS file. You could probably just generate one from the history of the 8.6.9 tag.
(Note: I'm no lawyer. I just followed some discussion in the past, especially regarding linking, so more the usage-case than the fork-case.)

**Comment by elextr** [comment] 2018-07-01 12:12
@ff200 well, its not the subject of this issue, which is about this specific project, the source is obviously available, its here on github, so you might be better asking on places dedicated to how to comply with the GPL, GNU themselves have several such resources.

**Comment by asciidoc3** [comment] 2018-07-08 17:08
see asciidoc3/asciidoc3

**Closed by asciidoc3** 2018-07-08 17:08 UTC
